version: '3'
services:
  flask:
    build: ./
    container_name: flask-project
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./:/store-web
    ports:
      - "5000:5000"
    command: python main.py
